# Examen parcial 3  (algebra lineal)
* Antes de enviar el archivo, $\textbf{reiniciar y ejecutar el kernel}$ para ver que el archivo se compila sin errores
* enviar el archivo jupyter sin anexos antes de las 10.00am del 14.09.2022 a mi dirección de correo electrónico: michal.hemmerling@udea.edu.co 

## Ejercicio 1.

En varios casos, sistema de equaciones diferentiales lineares
tipo 
$$\frac{d\textbf{x}}{dt}=\textbf{A}\textbf{x}$$
con solucion:
$$ \textbf{x}(t) = e^{t\textbf{A}} \textbf{C}$$

(donde $\textbf{x}$ es un vector, $\textbf{A}$ es matrix y $\textbf{C}$ es vector de condiciones iniciales)

se simplifica a calcular exponente de matriz: $e^{\textbf{A}t}$!!!!

$\textbf{Como ejercicio, calcule $e^{A}$}$ definido como:

$$e^A=Pe^DP^{-1}$$

donde $e^D$ es

$$e^D=
\begin{bmatrix}
e^{\lambda_1} & 0 & \cdots & 0 \\
0 & e^{\lambda_2} & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots\\
0 & 0 & \cdots & e^{\lambda_n} \\
\end{bmatrix}
$$

$P$ son eigenvectors y $P^{-1}$ es inversion de $P$

#### a) encuentra $e^A$ si:

$$A=
\begin{bmatrix}
1 &  -1 & -1 & -1\\
-1 &  2 & 0 & 0\\
-1 &  3 & 3 & 0 \\
-1 &  0 & 1 & 4 \\
\end{bmatrix}$$

#### b) Construye una function $\textbf{matrix_exp(A)}$ que acepta una matrix A como un argumento
#### c) si matrix no es cuadrada: imprime "Matrix must be square" y sale la funcion usando: $\textbf{return}$
#### d) si matrix es cuadrada ($\textbf{else:}$): calcule y imprime valor de $e^A$

In [1]:
import numpy as np

In [2]:
A = np.array([[1,-1,-1,-1],[-1,2,0,0],[-1,3,3,0],[-1,0,1,4]])
print('A \n',A)

A 
 [[ 1 -1 -1 -1]
 [-1  2  0  0]
 [-1  3  3  0]
 [-1  0  1  4]]


In [3]:
valores,vectores = np.linalg.eig(A)
P = vectores
print('Valores propios \n',valores)
print()
print('P \n',P)
print()
D = np.diag(valores)
print('D \n',D)
P_inv = np.linalg.inv(P)
print()
print('Inversa de P \n',P_inv)

Valores propios 
 [4.86619826 0.34455762 1.78924412 3.        ]

P 
 [[-3.49561271e-01  7.94033408e-01  7.62229110e-02  9.69367087e-16]
 [ 1.21959906e-01  4.79650284e-01  3.61664456e-01  3.63512658e-16]
 [ 3.83368157e-01 -2.42866291e-01 -8.33174113e-01 -7.07106781e-01]
 [ 8.46145115e-01  2.83659156e-01  4.11351172e-01  7.07106781e-01]]

D 
 [[4.86619826 0.         0.         0.        ]
 [0.         0.34455762 0.         0.        ]
 [0.         0.         1.78924412 0.        ]
 [0.         0.         0.         3.        ]]

Inversa de P 
 [[-0.5104852   0.79495719  0.58933991  0.58933991]
 [ 1.16666341  0.12636479  0.31915793  0.31915793]
 [-1.37511912  2.32933088 -0.6220131  -0.6220131 ]
 [ 0.94280904 -2.3570226  -0.47140452  0.94280904]]


In [4]:
# Creando e^D
Me = np.zeros((4,4))
for i in range(4):
  Me[i,i] = np.exp(1)

e = np.zeros((4,4))
for j in range(4):
  e[j,j] = Me[j,j]**D[j,j]
print('e^D \n',e) 

e^D 
 [[129.82641157   0.           0.           0.        ]
 [  0.           1.41136542   0.           0.        ]
 [  0.           0.           5.98492686   0.        ]
 [  0.           0.           0.          20.08553692]]


a)

In [5]:
# Calculando e^A
e_expA = P@e@P_inv
print('e^A \n',e_expA)

e^A 
 [[ 23.84711784 -34.8727468  -26.67167604 -26.67167604]
 [-10.2695345   17.71451082   8.20107077   8.20107077]
 [-32.34076479  61.38346694  39.01966047  18.93412354]
 [-45.60579958  59.63691501  56.64141472  76.72695165]]


In [6]:
def matrix_exp(A):
  B = np.copy(A)
  n = len(B)
  if n != len(B[0]):
    print("Matrix must be square" )
  
  else:
    valores,vectores = np.linalg.eig(B)
    P = vectores
    D = np.diag(valores)
    P_inv = np.linalg.inv(P)
    Me = np.zeros((n,n))
    for i in range(n):
      Me[i,i] = np.exp(1)

    e = np.zeros((n,n))
    for j in range(n):
      e[j,j] = Me[j,j]**D[j,j]

    e_expA = P@e@P_inv
    
  return e_expA


In [7]:
# Probando con matriz cuadrada
e_A = matrix_exp(A)
print(e_A)

[[ 23.84711784 -34.8727468  -26.67167604 -26.67167604]
 [-10.2695345   17.71451082   8.20107077   8.20107077]
 [-32.34076479  61.38346694  39.01966047  18.93412354]
 [-45.60579958  59.63691501  56.64141472  76.72695165]]


In [8]:
# Probando con matriz no cuadrada
C = np.array([[1,2,3],[2,0,1]])
e_A1 = matrix_exp(C)

Matrix must be square


UnboundLocalError: ignored

## Ejercicio 2.

Usando las leyes de circuito de Kirchhoff, es posible resolver el siguiente sistema:

![](https://raw.githubusercontent.com/sbustamante/ComputationalMethods/master/material/figures/circuit.png)

obteniendo las siguientes ecuaciones A,B,C: 

\begin{align}
A:&&I_A( R+4R ) - I_B( 4R ) =& E \\
C:&&-I_A( 4R ) + I_B( 4R + 3R ) - I_C(3R) =& 0 \\
B:&&-I_B( 3R ) + I_C(3R+2R) =& -2E\,
\end{align}

Encontre: $I_A, I_B, I_C$ usando: 

a) `scipy.linalg.solve`  
b) `scipy.linalg.inv(A)`  
c) `scipy.linalg.lu(A)`

*podemos substituir: $x_n=\frac{R I_n}{E}$ (n=A,B,C)

In [9]:
import scipy.linalg

In [10]:
# Luego de sustituir se llega al siguiente sistema de ecuaciones en forma matricial

M = np.array([[5,-4,0],[-4,7,-3],[0,-3,5]])
M_aumentada = np.array([[5,-4,0,1],[-4,7,-3,0],[0,-3,5,-2]])
b = np.array([[1],[0],[-2]])
print('M \n',M)
print()
print('M aumentada \n',M_aumentada)
print()
print('b \n',b)


M 
 [[ 5 -4  0]
 [-4  7 -3]
 [ 0 -3  5]]

M aumentada 
 [[ 5 -4  0  1]
 [-4  7 -3  0]
 [ 0 -3  5 -2]]

b 
 [[ 1]
 [ 0]
 [-2]]


In [11]:
Sol1 = np.linalg.solve(M,b)
print('Sol1 \n',Sol1)

Sol1 
 [[ 0.04]
 [-0.2 ]
 [-0.52]]


In [12]:
inv_M = np.linalg.inv(M)
print('Inversa de M \n',inv_M)
Sol2 = inv_M@b
print()
print('Sol2 \n',Sol2)

Inversa de M 
 [[0.52 0.4  0.24]
 [0.4  0.5  0.3 ]
 [0.24 0.3  0.38]]

Sol2 
 [[ 0.04]
 [-0.2 ]
 [-0.52]]


# Feedback:
```

    Exercise 1.
    Solution + presentation of the results	            (max 5.0p):	5.0p
- error esta aqui: D=np.diag(evalues)
    Exercise 2.
    Solution + presentation of the results	            (max 5.0p):	4.0p


    - Total:                                              (max 10.0p):   9.0p
```