# Examen parcial 3  (algebra lineal)
* Antes de enviar el archivo, $\textbf{reiniciar y ejecutar el kernel}$ para ver que el archivo se compila sin errores
* enviar el archivo jupyter sin anexos antes de las 10.00am del 14.09.2022 a mi dirección de correo electrónico: michal.hemmerling@udea.edu.co 

## Ejercicio 1.

En varios casos, resultan sistemas de ecuaciones diferenciales lineales del
tipo 
$$\frac{d\vec{x}}{dt}=\textbf{A}\vec{x}$$
con solucion:
$$ \vec{x}(t) = e^{t\textbf{A}} \vec{C}$$

(donde $\vec{x}$ es un vector, $\textbf{A}$ es matrix y $\vec{C}$ es vector de condiciones iniciales)

se reduce a calcular exponente de matriz: $e^{\textbf{A}t}$!!!!

$\textbf{Como ejercicio, calcule $e^{A}$}$ definido como:

$$e^A=Pe^DP^{-1}$$

donde $e^D$ es

$$e^D=
\begin{bmatrix}
e^{\lambda_1} & 0 & \cdots & 0 \\
0 & e^{\lambda_2} & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots\\
0 & 0 & \cdots & e^{\lambda_n} \\
\end{bmatrix}
$$

$P$ son la matriz con columnas de eigenvectores y $P^{-1}$ es la inversa de $P$

#### a) encuentra $e^A$ si:

$$A=
\begin{bmatrix}
1 &  -1 & -1 & -1\\
-1 &  2 & 0 & 0\\
-1 &  3 & 3 & 0 \\
-1 &  0 & 1 & 4 \\
\end{bmatrix}$$

#### b) Construye una función $\textbf{matrix_exp(A)}$ que acepta una matriz $A$ como un argumento
#### c) si la matriz no es cuadrada: imprime "Matrix must be square" y sale la funcion usando: $\textbf{return}$
#### d) si matrix es cuadrada ($\textbf{else:}$): calcule y imprime valor de $e^A$

In [17]:
import numpy as np

In [18]:
#Primeramente ingresamos la matriz A

A=np.array([[1,-1,-1,-1,],[-1,2,0,0],[-1,3,3,0],[-1,0,1,4]])

print(A)


[[ 1 -1 -1 -1]
 [-1  2  0  0]
 [-1  3  3  0]
 [-1  0  1  4]]


Inicialmente, verifico que haya quedado bien ingresada y algo muy importante! Que sea diagonalizable, puesto que en otro caso se requieren procedimientos adicionales. La manera más sencilla de identificar una matriz diagonalizable, es observando directamente sus valores propios. 
Puesto que los he de calcular, en caso de que la diagonalización exista, la determinaré de una vez

In [80]:
eigen, P = np.linalg.eig(A)

P_1=np.linalg.inv(A)
D=np.diag(eigen)

print(D)


[[4.86619826 0.         0.         0.        ]
 [0.         0.34455762 0.         0.        ]
 [0.         0.         1.78924412 0.        ]
 [0.         0.         0.         3.        ]]
[[-3.49561271e-01  7.94033408e-01  7.62229110e-02  9.69367087e-16]
 [ 1.21959906e-01  4.79650284e-01  3.61664456e-01  3.63512658e-16]
 [ 3.83368157e-01 -2.42866291e-01 -8.33174113e-01 -7.07106781e-01]
 [ 8.46145115e-01  2.83659156e-01  4.11351172e-01  7.07106781e-01]]


Al parecer hoy me ha acompañado la suerte, los valores propios son distintos, por lo tanto efectivamente la matriz es diagonalizable. 

In [81]:
#Sin embargo, algo hace meditar y es lo siguiente

print(P@D@P_1)

[[-4.2319188  -0.46038542 -1.01251924 -1.0579797 ]
 [ 1.51536977 -0.0514982   0.59454444  0.37884244]
 [ 3.87585322  0.92285184  0.64882271  0.43863322]
 [12.43314357  1.50017262  3.17684509  3.63861598]]


Tal como se puede ver, hay una cantidad notable de error de redondeo computacional en esta representación de la matriz. 
No lo incluí aquí, pero al verificar si los vectores propios satisfacen la definición, se obtienen ceros de un orden O(e-16) por lo cual confio en el cálculo, sin embargo, parece que este error se propaga un poco rápido con la multiplicación de las matrices. 

Por ahora continuaré. 
Sea E la matriz $e^{A}$, procedemos a calcularla tal como

In [82]:
E=P @ np.exp(D) @ P_1

print(E)

[[-117.56427563  -14.65711145  -29.13423993  -29.26089514]
 [  45.53374839    5.00934822   12.22521271   11.62425576]
 [ 116.85167253   14.77125023   28.60316209   25.48909523]
 [ 310.16544162   39.77171808   77.66231842   81.47730411]]


Esta es la matriz exponencial buscada. 

Construimos ahora la función solicitada

In [83]:
import math as mt

print(A.shape())

def matrix_exp(A):
  if (mt.abs(mt.floor((np.sqrt(A.shape())))!=0.0):
    print("Matrix must be square. Reconsider your entry values")
  else:

    eigen, P = np.linalg.eig(A)

    P_1=np.linalg.inv(A)
    D=np.diag(eigen)

    E=P @ np.exp(D) @ P_1

    return E

SyntaxError: ignored

## Ejercicio 2.

Usando las leyes de circuito de Kirchhoff, es posible resolver el siguiente sistema:

![](https://raw.githubusercontent.com/sbustamante/ComputationalMethods/master/material/figures/circuit.png)

obteniendo las siguientes ecuaciones A,B,C: 

\begin{align}
A:&&I_A( R+4R ) - I_B( 4R ) =& E \\
C:&&-I_A( 4R ) + I_B( 4R + 3R ) - I_C(3R) =& 0 \\
B:&&-I_B( 3R ) + I_C(3R+2R) =& -2E\,
\end{align}

Encontre: $I_A, I_B, I_C$ usando: 

a) `scipy.linalg.solve`  
b) `scipy.linalg.inv(A)`  
c) `scipy.linalg.lu(A)`

*podemos substituir: $x_n=\frac{R I_n}{E}$ (n=A,B,C)

En primer lugar  tómese la matriz de coeficientes del sistema

\begin{equation}
Z= \begin{bmatrix}
5 & -4 & 0\\
-4 & 7 & -3\\
0 & -3 & 5
\end{bmatrix} R
\end{equation}

y el vector de términos independientes

\begin{equation}
V_{0}= \begin{bmatrix}
1 \\
0 \\
-2 
\end{bmatrix} E
\end{equation}


In [49]:
B=np.array([[5,-4,0],[-4,7,-3],[0,-3,5]])

b=np.array([[1],[0],[-2]])

La solución puede obtenerse de diversas maneras, la primera es por eliminación gaussiana. 

Sea $I$ el vector asociado a las corrientes
El sistema de ecuaciones del circuito puede escribirse en forma matricial como

$$Z I = V_{0}$$

\begin{equation}
Z= R\begin{bmatrix}
5 & -4 & 0\\
-4 & 7 & -3\\
0 & -3 & 5
\end{bmatrix}  I =
V_{0}= \begin{bmatrix}
1 \\
0 \\
-2 
\end{bmatrix} E
\end{equation}

\begin{equation}
\begin{bmatrix}
5 & -4 & 0\\
-4 & 7 & -3\\
0 & -3 & 5
\end{bmatrix}  I =
\begin{bmatrix}
1 \\
0 \\
-2 
\end{bmatrix} \frac{E}{R} 
\end{equation}


$$B I = \left(\frac{E}{R}\right) b $$


Aplicar eliminación gaussiana consiste en multiplicar ambos lados de la igualdad por matrices elementales adecuadas (que corresponden a operaciones por renglón) dando una solución de la forma

$[Z|V_{0}] = $ 
$[E_{1}Z|E_{1}V_{0}] = [E_{n}...E_{1}Z|E_{n}...E_{1}V_{0}]$

hasta que la matriz

$E_{n}...E_{1}Z$ se encuentre en su forma escalonada reducida. Si esto se logra, la matriz

$I=E_{n}...E_{1}V_{0}$ es la solución del sistema. 

**Nótese que aquí $I$ denota un vector de corrientes, no la matriz identidad.** 

In [50]:
%matplotlib inline
import sympy as sym

In [60]:
I_gauss=np.linalg.solve(B,b)
print(I_gauss)

E,R=sym.symbols("E,R")

print("La solución al sistema es de la forma \n")
print((I_gauss)*E/R,3)

[[ 0.04]
 [-0.2 ]
 [-0.52]]
La solución al sistema es de la forma 

[[0.0400000000000001*E/R]
 [-0.2*E/R]
 [-0.52*E/R]] 3


Una manera alternativa de obtener esta misma solución, es calculando la matriz inversa de la matriz de coeficientes. En primer lugar verificamos si ésta existe. 

In [61]:
detZ = np.linalg.det(B)

if (detZ!=0.0):
  print("La matriz es invertible, proceda.")
else:
  print("Toda esperanza se ha perdido. Deberá usar un método distinto. ")

La matriz es invertible, proceda.


Confio en mi código, así que procederé. 

Cuando la matriz del sistema es invertible, tenemos


$Z I = V_{0}$


$Z^{-1}Z I=I = Z^{-1}V_{0}$

$I = Z^{-1}V_{0}$

es entonces la solución al sistema. 

In [62]:
B_1=np.linalg.inv(B)

I_inverse=B_1@b
print(I_inverse)
print("La solución al sistema es de la forma \n")
print((I_inverse)*E/R)


[[ 0.04]
 [-0.2 ]
 [-0.52]]
La solución al sistema es de la forma 

[[0.04*E/R]
 [-0.2*E/R]
 [-0.52*E/R]]


Respuesta que coincide con el otro método, tal como debería ser. 

Por último, procedemos con el último de los métodos, obteniendo una factoriación LU para la matriz de coeficientes del sistema

In [63]:
#necesito en este caso una función de Scipy
import scipy.linalg as la

Q, L, U = la.lu(B)



Junto con estas matrices tenemos de nuevo

$$A I = \left(\frac{E}{R}\right) b $$

$$ P L U I = \left(\frac{E}{R}\right) b $$

Sea $UI = y$

Resolvemos para $PL y= \left(\frac{E}{R}\right) b$

In [64]:
y=np.linalg.inv(Q) @  np.linalg.inv(L) @ b

Y ahora, se retorna de la sustitución

In [65]:
I_plu=np.linalg.inv(U) @ y
print(I_plu)
print("La solución al sistema es de la forma \n")
print((I_plu)*E/R)

[[ 0.04]
 [-0.2 ]
 [-0.52]]
La solución al sistema es de la forma 

[[0.0400000000000001*E/R]
 [-0.2*E/R]
 [-0.52*E/R]]


# Feedback:
```

    Exercise 1.
    Solution + presentation of the results	            (max 5.0p):	2.0p
- error esta aqui: D=np.diag(eigen)
    Exercise 2.
    Solution + presentation of the results	            (max 5.0p):	5.0p


    - Total:                                              (max 10.0p):   7.0p
```