#Santiago Herrera Guzmán
##CC. 1010157719

In [96]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg

# Examen parcial 3  (algebra lineal)
* Antes de enviar el archivo, $\textbf{reiniciar y ejecutar el kernel}$ para ver que el archivo se compila sin errores
* enviar el archivo jupyter sin anexos antes de las 10.00am del 14.09.2022 a mi dirección de correo electrónico: michal.hemmerling@udea.edu.co 

## Ejercicio 1.

En varios casos, sistema de equaciones diferentiales lineares
tipo 
$$\frac{d\textbf{x}}{dt}=\textbf{A}\textbf{x}$$
con solucion:
$$ \textbf{x}(t) = e^{t\textbf{A}} \textbf{C}$$

(donde $\textbf{x}$ es un vector, $\textbf{A}$ es matrix y $\textbf{C}$ es vector de condiciones iniciales)

se simplifica a calcular exponente de matriz: $e^{\textbf{A}t}$!!!!

$\textbf{Como ejercicio, calcule $e^{A}$}$ definido como:

$$e^A=Pe^DP^{-1}$$

donde $e^D$ es

$$e^D=
\begin{bmatrix}
e^{\lambda_1} & 0 & \cdots & 0 \\
0 & e^{\lambda_2} & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots\\
0 & 0 & \cdots & e^{\lambda_n} \\
\end{bmatrix}
$$

$P$ son eigenvectors y $P^{-1}$ es inversion de $P$

#### a) encuentra $e^A$ si:

$$A=
\begin{bmatrix}
1 &  -1 & -1 & -1\\
-1 &  2 & 0 & 0\\
-1 &  3 & 3 & 0 \\
-1 &  0 & 1 & 4 \\
\end{bmatrix}$$

#### b) Construye una function $\textbf{matrix_exp(A)}$ que acepta una matrix A como un argumento
#### c) si matrix no es cuadrada: imprime "Matrix must be square" y sale la funcion usando: $\textbf{return}$
#### d) si matrix es cuadrada ($\textbf{else:}$): calcule y imprime valor de $e^A$

Para lograr ésto, primero definimos la matriz A de la siguiente forma:

In [97]:
A=np.array([[1,-1,-1,-1],
            [-1,2,0,0],
            [-1,3,3,0], 
            [-1,0,1,4]])


Ahora definimos una función que me va a devolver el valor de la ecuación que queremos, es decir:
$$e^A  $$

In [98]:
def matrix_exp(A):

  if np.shape(A)[0] != np.shape(A)[1]: #Condición si la matriz no es cuadrada

    return print("Matrix must be square") 


  else:

    evalues, evectors = np.linalg.eig(A) #Encuentro Valores propios de valores y vectores propios

    P = evectors #Matriz P
    P_inv = np.linalg.inv(P) #Matriz P invertida

    e_D= np.diag(np.exp(evalues)) #Creo la matriz e^D
    
    return P@e_D@P_inv

  


In [99]:
print('El valor de e^A es:')
print(matrix_exp(A))

El valor de e^A es:
[[ 23.84711784 -34.8727468  -26.67167604 -26.67167604]
 [-10.2695345   17.71451082   8.20107077   8.20107077]
 [-32.34076479  61.38346694  39.01966047  18.93412354]
 [-45.60579958  59.63691501  56.64141472  76.72695165]]


## Ejercicio 2.

Usando las leyes de circuito de Kirchhoff, es posible resolver el siguiente sistema:

![](https://raw.githubusercontent.com/sbustamante/ComputationalMethods/master/material/figures/circuit.png)

obteniendo las siguientes ecuaciones A,B,C: 

\begin{align}
A:&&I_A( R+4R ) - I_B( 4R ) =& E \\
C:&&-I_A( 4R ) + I_B( 4R + 3R ) - I_C(3R) =& 0 \\
B:&&-I_B( 3R ) + I_C(3R+2R) =& -2E\,
\end{align}

Encontre: $I_A, I_B, I_C$ usando: 

a) `scipy.linalg.solve`  
b) `scipy.linalg.inv(A)`  
c) `scipy.linalg.lu(A)`

*podemos substituir: $x_n=\frac{R I_n}{E}$ (n=A,B,C)

Para lograr lo propuesto, vamos a usar la sustitución sugerida y el sistema queda de la siguiente forma:

$$ \begin{pmatrix}
5 & 4 & 0 \\
-4 & 7 & -3 \\
0 & -3 & 5 
\end{pmatrix}  \begin{pmatrix}
I_1\\
I_2\\
I_3
\end{pmatrix} = \begin{pmatrix}
1\\
0\\
-2
\end{pmatrix} $$

A)

In [100]:
matriz = np.array([[5,-4,0],  
            [-4,7,-3],
            [0,-3,5]])  #Creo la matriz que usando el cambio de variable

b = np.array([[1],[0],[-2]]) # Creo la matriz b con las soluciones

In [101]:
soluciones_solve = scipy.linalg.solve(matriz,b) #Solucion usando linalg.solve
soluciones_solve 
print('Solución para cada Intensidad usando función de numpy')
print(f'Variable \t Valor')
print('='*30)
print(f'I_1 \t\t {round(soluciones_solve[0][0],3)}')
print(f'I_2 \t\t {round(soluciones_solve[1][0],3)}')
print(f'I_3 \t\t {round(soluciones_solve[2][0],3)}')

Solución para cada Intensidad usando función de numpy
Variable 	 Valor
I_1 		 0.04
I_2 		 -0.2
I_3 		 -0.52


B)

Para ésto vamos a sacar la inversa de la matriz inicial y luego hacemos la siguiente operación: 
$$ I_n = A^{-1}  b_n$$

In [102]:
matriz_inv = np.linalg.inv(matriz)

In [103]:
soluciones_inv = matriz_inv@b

In [104]:
print('Solución para cada Intensidad usando la inversa de la matriz')
print(f'Variable \t Valor')
print('='*30)
print(f'I_1 \t\t {round(soluciones_inv[0][0],3)}')
print(f'I_2 \t\t {round(soluciones_inv[1][0],3)}')
print(f'I_3 \t\t {round(soluciones_inv[2][0],3)}')

Solución para cada Intensidad usando la inversa de la matriz
Variable 	 Valor
I_1 		 0.04
I_2 		 -0.2
I_3 		 -0.52


C)

Para hacer ésto. hacemos la siguiente descomposición:
$$A = LU$$

Y resolvemos los siguientes sistemas:
$$U x_n = y_n$$

$$L y_n = b_n$$

In [105]:
P, L, U = scipy.linalg.lu(matriz) #Descompongo la matriz
solucion1 = np.linalg.solve(L,b) #Hallo los valores de y
solucion_final = np.linalg.solve(U,solucion1) #Hallo los valores de b


In [106]:
print('Solución para cada Intensidad usando la matriz diagonal')
print(f'Variable \t Valor')
print('='*30)
print(f'I_1 \t\t {round(solucion_final[0][0],3)}')
print(f'I_2 \t\t {round(solucion_final[1][0],3)}')
print(f'I_3 \t\t {round(solucion_final[2][0],3)}')

Solución para cada Intensidad usando la matriz diagonal
Variable 	 Valor
I_1 		 0.04
I_2 		 -0.2
I_3 		 -0.52


# Feedback:
```

    Exercise 1.
    Solution + presentation of the results	            (max 5.0p):	5.0p

    Exercise 2.
    Solution + presentation of the results	            (max 5.0p):	5.0p


    - Total:                                              (max 10.0p):   10.0p
```