# Examen parcial 3  (algebra lineal)
* Antes de enviar el archivo, $\textbf{reiniciar y ejecutar el kernel}$ para ver que el archivo se compila sin errores
* enviar el archivo jupyter sin anexos antes de las 10.00am del 14.09.2022 a mi dirección de correo electrónico: michal.hemmerling@udea.edu.co 

## Ejercicio 1.

En varios casos, sistema de equaciones diferentiales lineares
tipo 
$$\frac{d\textbf{x}}{dt}=\textbf{A}\textbf{x}$$
con solucion:
$$ \textbf{x}(t) = e^{t\textbf{A}} \textbf{C}$$

(donde $\textbf{x}$ es un vector, $\textbf{A}$ es matrix y $\textbf{C}$ es vector de condiciones iniciales)

se simplifica a calcular exponente de matriz: $e^{\textbf{A}t}$!!!!

$\textbf{Como ejercicio, calcule $e^{A}$}$ definido como:

$$e^A=Pe^DP^{-1}$$

donde $e^D$ es

$$e^D=
\begin{bmatrix}
e^{\lambda_1} & 0 & \cdots & 0 \\
0 & e^{\lambda_2} & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots\\
0 & 0 & \cdots & e^{\lambda_n} \\
\end{bmatrix}
$$

$P$ son eigenvectors y $P^{-1}$ es inversion de $P$

#### a) encuentra $e^A$ si:

$$A=
\begin{bmatrix}
1 &  -1 & -1 & -1\\
-1 &  2 & 0 & 0\\
-1 &  3 & 3 & 0 \\
-1 &  0 & 1 & 4 \\
\end{bmatrix}$$

#### b) Construye una function $\textbf{matrix_exp(A)}$ que acepta una matrix A como un argumento
#### c) si matrix no es cuadrada: imprime "Matrix must be square" y sale la funcion usando: $\textbf{return}$
#### d) si matrix es cuadrada ($\textbf{else:}$): calcule y imprime valor de $e^A$

In [2]:
import numpy as np
A = np.array([[1,-1,-1,-1],[-1,2,0,0],[-1,3,3,0],[-1,0,1,4]])
evalues, evectors = np.linalg.eig(A)
P = evectors
Pinv=np.linalg.inv(P)
D = np.zeros((4,4))
for i in range(4):
    D[i,i] = np.exp(evalues[i])
eA = P@D@Pinv
eA

array([[ 23.84711784, -34.8727468 , -26.67167604, -26.67167604],
       [-10.2695345 ,  17.71451082,   8.20107077,   8.20107077],
       [-32.34076479,  61.38346694,  39.01966047,  18.93412354],
       [-45.60579958,  59.63691501,  56.64141472,  76.72695165]])

In [6]:
def matrix_exp(A):
    B = np.copy(A)
    R,C = B.shape
    if R != C:
        return print("Matrix must be square")
    else: 
        evalues, evectors = np.linalg.eig(B)
        P = evectors
        Pinv=np.linalg.inv(P)
        D = np.zeros((R,C))
        for i in range(R):
            D[i,i] = np.exp(evalues[i])
        eA = P@D@Pinv
        return eA
A1 = np.array([[1,-1,-1],[-1,2,0],[-1,3,3],[-1,0,1]])
matrix_exp(A1)
A2 =np.array([[2,1,3],[4,-1,3],[-1,5,5]])
matrix_exp(A2)

Matrix must be square


array([[ 217.10043954,  509.86426626,  835.31014706],
       [ 216.96510426,  509.99960155,  835.31014706],
       [ 329.06060458,  784.68625816, 1283.83813717]])

## Ejercicio 2.

Usando las leyes de circuito de Kirchhoff, es posible resolver el siguiente sistema:

![](https://raw.githubusercontent.com/sbustamante/ComputationalMethods/master/material/figures/circuit.png)

obteniendo las siguientes ecuaciones A,B,C: 

\begin{align}
A:&&I_A( R+4R ) - I_B( 4R ) =& E \\
C:&&-I_A( 4R ) + I_B( 4R + 3R ) - I_C(3R) =& 0 \\
B:&&-I_B( 3R ) + I_C(3R+2R) =& -2E\,
\end{align}

Encontre: $I_A, I_B, I_C$ usando: 

a) `scipy.linalg.solve`  
b) `scipy.linalg.inv(A)`  
c) `scipy.linalg.lu(A)`

*podemos substituir: $x_n=\frac{R I_n}{E}$ (n=A,B,C)

In [3]:
import scipy.linalg
R = 1
E = 1
S = np.array([[5*R,-4*R,0],[-4*R,7*R,-3*R],[0,-3*R,5*R]])
B = np.array([E,0,-2*E])

x1 = scipy.linalg.solve(S,B)
x1

array([ 0.04, -0.2 , -0.52])

In [4]:
S_inv = scipy.linalg.inv(S)
x2 = S_inv@B
x2

array([ 0.04, -0.2 , -0.52])

In [5]:
from scipy.linalg import lu_factor, lu_solve
lu, piv = lu_factor(S)
x3 = lu_solve((lu, piv), B)
x3

array([ 0.04, -0.2 , -0.52])

# Feedback:
```

    Exercise 1.
    Solution + presentation of the results	            (max 5.0p):	5.0p

    Exercise 2.
    Solution + presentation of the results	            (max 5.0p):	5.0p


    - Total:                                              (max 10.0p):   10.0p
```