# Class exercises 2:

Consider:

$$-R1I1-R2I2-R3I3=-E1$$

$$R2I2-R4I4=-E2$$

$$R3I3-R5I5=E2$$

$$I1-I3-I5=0$$

$$-I1+I2+I4=0$$

$$-I4+I5+I6=0$$


The set of linear equations comes from the Kirchhoff's rules (in case of doubts review the literature)

Find the currents $I_1 \cdots I_6$ knowing that the 

Resistances are:

$R_1=1 \Omega$,
$R_2=2 \Omega$,
$R_3=3 \Omega$,
$R_4=4 \Omega$,
$R_5=5 \Omega$

Voltages are:
$E_1=10 V$,
$E_2=40 V$

use python build in functions  `np.linalg.solve(A,b)`

In [1]:
import numpy as np

In [2]:
List1 = [[-1,-2,-3,0,0,0],[0,2,0,-4,0,0],[0,0,3,0,-5,0],[1,0,-1,0,-1,0],[-1,1,0,1,0,0],[0,0,0,-1,1,1]] 
A = np.array(List1)
b = np.array([[10],
              [-40],
              [40],
              [0],
              [0],
              [0]])
print('A \n',A)
print()
print('b \n',b)

A 
 [[-1 -2 -3  0  0  0]
 [ 0  2  0 -4  0  0]
 [ 0  0  3  0 -5  0]
 [ 1  0 -1  0 -1  0]
 [-1  1  0  1  0  0]
 [ 0  0  0 -1  1  1]]

b 
 [[ 10]
 [-40]
 [ 40]
 [  0]
 [  0]
 [  0]]


In [3]:
x = np.linalg.solve(A,b)
print(x)

[[-2.77227723]
 [-8.51485149]
 [ 3.26732673]
 [ 5.74257426]
 [-6.03960396]
 [11.78217822]]


In [4]:
print('I1 = ',x[0,0])
print('I2 = ',x[1,0])
print('I3 = ',x[2,0])
print('I4 = ',x[3,0])
print('I5 = ',x[4,0])
print('I6 = ',x[5,0])

I1 =  -2.772277227722771
I2 =  -8.514851485148515
I3 =  3.267326732673267
I4 =  5.742574257425743
I5 =  -6.03960396039604
I6 =  11.782178217821784
