# Examen parcial 3  (algebra lineal)
* Antes de enviar el archivo, $\textbf{reiniciar y ejecutar el kernel}$ para ver que el archivo se compila sin errores
* enviar el archivo jupyter sin anexos antes de las 10.00am del 14.09.2022 a mi dirección de correo electrónico: michal.hemmerling@udea.edu.co 

#Karla Daniela Castro Mesa

## Ejercicio 1.

En varios casos, sistema de equaciones diferentiales lineares
tipo 
$$\frac{d\textbf{x}}{dt}=\textbf{A}\textbf{x}$$
con solucion:
$$ \textbf{x}(t) = e^{t\textbf{A}} \textbf{C}$$

(donde $\textbf{x}$ es un vector, $\textbf{A}$ es matrix y $\textbf{C}$ es vector de condiciones iniciales)

se simplifica a calcular exponente de matriz: $e^{\textbf{A}t}$!!!!

$\textbf{Como ejercicio, calcule $e^{A}$}$ definido como:

$$e^A=Pe^DP^{-1}$$

donde $e^D$ es

$$e^D=
\begin{bmatrix}
e^{\lambda_1} & 0 & \cdots & 0 \\
0 & e^{\lambda_2} & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots\\
0 & 0 & \cdots & e^{\lambda_n} \\
\end{bmatrix}
$$

$P$ son eigenvectors y $P^{-1}$ es inversion de $P$

#### a) encuentra $e^A$ si:

$$A=
\begin{bmatrix}
1 &  -1 & -1 & -1\\
-1 &  2 & 0 & 0\\
-1 &  3 & 3 & 0 \\
-1 &  0 & 1 & 4 \\
\end{bmatrix}$$

#### b) Construye una function $\textbf{matrix_exp(A)}$ que acepta una matrix A como un argumento
#### c) si matrix no es cuadrada: imprime "Matrix must be square" y sale la funcion usando: $\textbf{return}$
#### d) si matrix es cuadrada ($\textbf{else:}$): calcule y imprime valor de $e^A$

In [27]:
import math
from math import e
import numpy as np
A= np.array([[1,-1,-1,-1],
             [-1,2,0,0],
             [-1,3,3,0],
             [-1,0,1,4]])

print(A,'\n')
print()
print('e**A es:','\n' ,e**A,'\n')


[[ 1 -1 -1 -1]
 [-1  2  0  0]
 [-1  3  3  0]
 [-1  0  1  4]] 


e**A es: 
 [[ 2.71828183  0.36787944  0.36787944  0.36787944]
 [ 0.36787944  7.3890561   1.          1.        ]
 [ 0.36787944 20.08553692 20.08553692  1.        ]
 [ 0.36787944  1.          2.71828183 54.59815003]] 



In [28]:
def matrix_exp(A):
  n = len(A)
  try:
    detA = np.linalg.det(A)
    print('Una matriz cuadrada: ')
  except:
    raise TypeError( "Matrix must be square" )
    return matrix_exp(A)

In [29]:
A=np.array([[1,-1,-1,-1],
             [-1,2,0,0],
             [-1,3,3,0],
             [-1,0,1,4]])

evalues, evectors = np.linalg.eig(A)

P = evectors
P_1 = np.linalg.inv(evectors)


D=np.diag(evalues)

print('D=\n',D)
print('\n')

print('A=\n',A)

print('PDP_1=\n',P@D@P_1)

print('PP_1=\n',P@P_1)

D=
 [[4.86619826 0.         0.         0.        ]
 [0.         0.34455762 0.         0.        ]
 [0.         0.         1.78924412 0.        ]
 [0.         0.         0.         3.        ]]


A=
 [[ 1 -1 -1 -1]
 [-1  2  0  0]
 [-1  3  3  0]
 [-1  0  1  4]]
PDP_1=
 [[ 1.00000000e+00 -1.00000000e+00 -1.00000000e+00 -1.00000000e+00]
 [-1.00000000e+00  2.00000000e+00 -1.24594257e-15  7.43613212e-16]
 [-1.00000000e+00  3.00000000e+00  3.00000000e+00  1.28664595e-15]
 [-1.00000000e+00  2.19338133e-15  1.00000000e+00  4.00000000e+00]]
PP_1=
 [[ 1.00000000e+00 -6.43740857e-17  4.95752280e-17  3.26885282e-17]
 [ 9.65611286e-18  1.00000000e+00 -3.25836320e-17  9.65611286e-18]
 [ 1.11022302e-16 -2.22044605e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [30]:
D=np.diag(evalues)

In [31]:
D

array([[4.86619826, 0.        , 0.        , 0.        ],
       [0.        , 0.34455762, 0.        , 0.        ],
       [0.        , 0.        , 1.78924412, 0.        ],
       [0.        , 0.        , 0.        , 3.        ]])

In [32]:
P

array([[-3.49561271e-01,  7.94033408e-01,  7.62229110e-02,
         9.69367087e-16],
       [ 1.21959906e-01,  4.79650284e-01,  3.61664456e-01,
         3.63512658e-16],
       [ 3.83368157e-01, -2.42866291e-01, -8.33174113e-01,
        -7.07106781e-01],
       [ 8.46145115e-01,  2.83659156e-01,  4.11351172e-01,
         7.07106781e-01]])

In [33]:
P_1=np.linalg.inv(P)
P_1

array([[-0.5104852 ,  0.79495719,  0.58933991,  0.58933991],
       [ 1.16666341,  0.12636479,  0.31915793,  0.31915793],
       [-1.37511912,  2.32933088, -0.6220131 , -0.6220131 ],
       [ 0.94280904, -2.3570226 , -0.47140452,  0.94280904]])

In [34]:
A = np.array([[1,-1,-1,-1],
             [-1,2,0,0],
             [-1,3,3,0],
             [-1,0,1,4]])
evalues,evectors=np.linalg.eig(A)
print('A:\n',A)
print('Eigen vectors:\n', evectors)
print('Eigen values:\n', evalues)

A:
 [[ 1 -1 -1 -1]
 [-1  2  0  0]
 [-1  3  3  0]
 [-1  0  1  4]]
Eigen vectors:
 [[-3.49561271e-01  7.94033408e-01  7.62229110e-02  9.69367087e-16]
 [ 1.21959906e-01  4.79650284e-01  3.61664456e-01  3.63512658e-16]
 [ 3.83368157e-01 -2.42866291e-01 -8.33174113e-01 -7.07106781e-01]
 [ 8.46145115e-01  2.83659156e-01  4.11351172e-01  7.07106781e-01]]
Eigen values:
 [4.86619826 0.34455762 1.78924412 3.        ]


In [35]:
A=np.array([[1,-1,-1,-1],
             [-1,2,0,0],
             [-1,3,3,0],
             [-1,0,1,4]])

evalues, evectors = np.linalg.eig(A)

print(A)
print('\n')


print('\n')
print(evalues)

print('\n')

print(evectors)

[[ 1 -1 -1 -1]
 [-1  2  0  0]
 [-1  3  3  0]
 [-1  0  1  4]]




[4.86619826 0.34455762 1.78924412 3.        ]


[[-3.49561271e-01  7.94033408e-01  7.62229110e-02  9.69367087e-16]
 [ 1.21959906e-01  4.79650284e-01  3.61664456e-01  3.63512658e-16]
 [ 3.83368157e-01 -2.42866291e-01 -8.33174113e-01 -7.07106781e-01]
 [ 8.46145115e-01  2.83659156e-01  4.11351172e-01  7.07106781e-01]]


In [36]:
A=np.array([[1,-1,-1,-1],
             [-1,2,0,0],
             [-1,3,3,0],
             [-1,0,1,4]])


detA=np.linalg.det(A)

evalues, evectors = np.linalg.eig(A)

## Ejercicio 2.

Usando las leyes de circuito de Kirchhoff, es posible resolver el siguiente sistema:

![](https://raw.githubusercontent.com/sbustamante/ComputationalMethods/master/material/figures/circuit.png)

obteniendo las siguientes ecuaciones A,B,C: 

\begin{align}
A:&&I_A( R+4R ) - I_B( 4R ) =& E \\
C:&&-I_A( 4R ) + I_B( 4R + 3R ) - I_C(3R) =& 0 \\
B:&&-I_B( 3R ) + I_C(3R+2R) =& -2E\,
\end{align}

Encontre: $I_A, I_B, I_C$ usando: 

a) `scipy.linalg.solve`  
b) `scipy.linalg.inv(A)`  
c) `scipy.linalg.lu(A)`

*podemos substituir: $x_n=\frac{R I_n}{E}$ (n=A,B,C)

In [1]:
import numpy as np
import scipy.linalg

#Punto 2A
M= np.array([[5,-4,0],
            [-4,7,-3],
            [0,-3,5]])

b=np.array([[1],
            [0],
            [-2]])

print('Solving: Mx=b\n')
print('M=\n',M)
print()
print('b=\n',b)
print()
x=np.linalg.solve(M, b)
print(x)

Solving: Mx=b

M=
 [[ 5 -4  0]
 [-4  7 -3]
 [ 0 -3  5]]

b=
 [[ 1]
 [ 0]
 [-2]]

[[ 0.04]
 [-0.2 ]
 [-0.52]]


In [2]:
#Punto 2B

import numpy as np

M=np.array([[5,-4,0],
            [-4,7,-3],
            [0,-3,5]])

M_inv=np.linalg.inv(M)
print('\nM=\n',M)

print('\nM^-1 =\n',M_inv)

print('\nM M^-1 =\n',np.matmul(M,M_inv))


M=
 [[ 5 -4  0]
 [-4  7 -3]
 [ 0 -3  5]]

M^-1 =
 [[0.52 0.4  0.24]
 [0.4  0.5  0.3 ]
 [0.24 0.3  0.38]]

M M^-1 =
 [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 2.22044605e-16  1.00000000e+00 -1.66533454e-16]
 [ 0.00000000e+00  1.66533454e-16  1.00000000e+00]]


In [3]:
M= np.array([[5,-4,0],
            [-4,7,-3],
            [0,-3,5]])

b=np.array([[1],
            [0],
            [-2]])

print('M=\n',M)
print()
M_inv=np.linalg.inv(M)
print('Minv=\n',M_inv)
print()
print('Minv x b=\n',M_inv@b)

M=
 [[ 5 -4  0]
 [-4  7 -3]
 [ 0 -3  5]]

Minv=
 [[0.52 0.4  0.24]
 [0.4  0.5  0.3 ]
 [0.24 0.3  0.38]]

Minv x b=
 [[ 0.04]
 [-0.2 ]
 [-0.52]]


In [4]:
#Punto 2C
import scipy.linalg
import numpy as np
M=np.array([[5,-4,0],
            [-4,7,-3],
            [0,-3,5]])
print(M)
print()
P, L, U = scipy.linalg.lu(M)
print()
print(P)
print()
print(L)
print()
print(U)
print()
print(P@L@U)

[[ 5 -4  0]
 [-4  7 -3]
 [ 0 -3  5]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[ 1.          0.          0.        ]
 [-0.8         1.          0.        ]
 [ 0.         -0.78947368  1.        ]]

[[ 5.         -4.          0.        ]
 [ 0.          3.8        -3.        ]
 [ 0.          0.          2.63157895]]

[[ 5. -4.  0.]
 [-4.  7. -3.]
 [ 0. -3.  5.]]


In [5]:
import scipy.linalg
M= np.array([[5,-4,0],
            [-4,7,-3],
            [0,-3,5]])
P, L, U = scipy.linalg.lu(M)
print('\nM=\n',M)
print('\nP matmul A\n',np.matmul(P,M))
print('\nL matmul U\n',np.matmul(L,U))


M=
 [[ 5 -4  0]
 [-4  7 -3]
 [ 0 -3  5]]

P matmul A
 [[ 5. -4.  0.]
 [-4.  7. -3.]
 [ 0. -3.  5.]]

L matmul U
 [[ 5. -4.  0.]
 [-4.  7. -3.]
 [ 0. -3.  5.]]


# Feedback:
```

    Exercise 1.
    Solution + presentation of the results	            (max 5.0p):	3.0p
- error esta aqui: D=np.diag(evalues)
    Exercise 2.
    Solution + presentation of the results	            (max 5.0p):	4.0p


    - Total:                                              (max 10.0p):   7.0p
```